### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by ham604** [ham604/protospace-34254#1]
#URL
https://protospace-34254.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **正しくプロトタイプを編集できた場合は、詳細ページへ遷移するようにしましょう**
現状、トップページへ遷移してしまいます

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
詳細ページのユーザー名をクリックしたとき、トップページに遷移してしまいます
<img width="709" alt="スクリーンショット_2021-04-04_11_32_11" src="https://user-images.githubusercontent.com/62644781/113496966-e6a24200-9539-11eb-8c08-83e97f4897a3.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@ham604 さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
